'use client';
import { useEffect,useMemo,useState } from 'react';
import Scanner from './Scanner';
const MEDIA=[['book','📚','Books'],['vhs','📼','VHS'],['cd','💿','CDs'],['dvd','📀','DVDs']];
const SORTS=[['title','A–Z'],['titleDesc','Z–A'],['newest','Newest added'],['oldest','Oldest added']];
const clean=s=>String(s??'').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
export default function Home(){
 const[items,setItems]=useState([]),[media,setMedia]=useState('book'),[sort,setSort]=useState('title'),[title,setTitle]=useState(''),[status,setStatus]=useState(''),[suggestions,setSuggestions]=useState([]),[searching,setSearching]=useState(false),[adding,setAdding]=useState(false);
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem('shelfhunt-wanted')||'[]'))}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem('shelfhunt-wanted',JSON.stringify(items))}catch{}},[items]);
 useEffect(()=>{const q=clean(title);if(q.length<2){setSearching(false);if(!q)setSuggestions([]);return}let cancelled=false;const timer=setTimeout(async()=>{setSearching(true);try{const r=await fetch(`/api/search?q=${encodeURIComponent(q)}&media=${encodeURIComponent(media)}`,{cache:'no-store'});const data=await r.json();if(!cancelled&&Array.isArray(data.results)&&data.results.length)setSuggestions(data.results)}catch{}finally{if(!cancelled)setSearching(false)}},180);return()=>{cancelled=true;clearTimeout(timer)}},[title,media]);
 function add(t=title,m=media){const value=clean(t),mediaType=clean(m).toLowerCase();if(!value){setStatus('Type or select an item first.');return}if(adding)return;setAdding(true);const exists=items.some(i=>norm(i.title)===norm(value)&&norm(i.media_type)===norm(mediaType));if(exists){setStatus(`“${value}” is already on your list.`);setAdding(false);return}const item={id:`local-${Date.now()}-${Math.random().toString(36).slice(2)}`,title:value,media_type:mediaType,created_at:new Date().toISOString()};setItems(prev=>[...prev,item]);setTitle('');setSuggestions([]);setStatus(`✓ Added “${value}” to your ${MEDIA.find(x=>x[0]===mediaType)?.[2].toLowerCase()||'media'} wanted list.`);setAdding(false)}
 function remove(id){setItems(prev=>prev.filter(i=>i.id!==id));setStatus('Item removed.');}
 const visible=useMemo(()=>items.filter(i=>norm(i.media_type)===norm(media)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='titleDesc'?b.title.localeCompare(a.title):sort==='newest'?new Date(b.created_at)-new Date(a.created_at):new Date(a.created_at)-new Date(b.created_at)),[items,media,sort]);
 const iconFor=t=>t==='book'?'📚':t==='movie'?'🎬':t==='music'?'🎵':t==='dvd'?'📀':t==='vhs'?'📼':'💿';
 return <><header className="header"><div className="logo">🔎 ShelfHunt</div><div className="tagline">Find what you're hunting for.</div></header><main className="container"><section className="card"><div className="row between"><div><h2>📋 Wanted Lists</h2><div className="small">Choose the media type first, then search. No account required while we're testing.</div></div><span className="count">{items.length} total</span></div><div className="mediaGrid">{MEDIA.map(([key,icon,label])=><button key={key} className={media===key?'media active':'media'} onClick={()=>{setMedia(key);setSuggestions([]);setTitle('');setStatus('')}}><span>{icon}</span>{label}<b>{items.filter(i=>norm(i.media_type)===key).length}</b></button>)}</div><select value={sort} onChange={e=>setSort(e.target.value)}>{SORTS.map(([v,l])=><option key={v} value={v}>Sort: {l}</option>)}</select><div className="addRow"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={`Search ${MEDIA.find(x=>x[0]===media)?.[2].toLowerCase()}...`} onKeyDown={e=>e.key==='Enter'&&add()}/><button type="button" disabled={adding} onClick={()=>add()}>{adding?'Adding…':'Add'}</button></div>{(searching||suggestions.length>0)&&<div className="suggestions"><div className="suggestTitle">{searching?'Updating suggestions…':'Choose a match, or keep typing:'}</div>{suggestions.map((s,i)=><button type="button" className="suggestion" key={`${s.type}-${s.id}-${i}`} onMouseDown={e=>e.preventDefault()} onClick={e=>{e.preventDefault();add(s.title,media)}}><span><b>{s.title}</b><small>{s.subtitle}{s.year?` · ${s.year}`:''}</small></span><strong>{iconFor(s.type)}</strong></button>)}</div>}{status&&<div className="message">{status}</div>}<div className="list">{visible.length?visible.map(i=><div className="item" key={i.id}><span>{MEDIA.find(x=>x[0]===norm(i.media_type))?.[1]} {i.title}</span><button className="remove" onClick={()=>remove(i.id)}>Remove</button></div>):<div className="empty">No {MEDIA.find(x=>x[0]===media)?.[2].toLowerCase()} on this list yet.</div>}</div></section><Scanner wantedItems={items.filter(i=>norm(i.media_type)===norm(media)).map(i=>i.title)} media={media}/><section className="card"><h2>🔒 Accounts & Pro — coming after testing</h2><p className="small">We're keeping accounts, paid features, delayed alerts, rare-item services, and cloud syncing out of the test version until the core search and scanner are reliable.</p></section></main></>;
}