'use client';
import Script from 'next/script';
import { useEffect,useRef,useState } from 'react';
const normalize=s=>(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function matchWanted(text,wantedItems){const n=normalize(text);if(n.length<3)return null;let best=null,bestScore=0;for(const item of wantedItems){const w=normalize(item);if(w.length<3)continue;if(n.includes(w)||w.includes(n))return item;const words=w.split(/\s+/).filter(x=>x.length>1);const hits=words.filter(x=>n.includes(x)).length;const score=words.length?hits/words.length:0;if(score>bestScore){bestScore=score;best=item}}return bestScore>=0.5?best:null}
export default function Scanner({wantedItems=[],media='book'}){const videoRef=useRef(null),streamRef=useRef(null),scanningRef=useRef(false),ocrBusyRef=useRef(false),workerRef=useRef(null),barcodeRef=useRef(null),lastAlertRef=useRef({item:'',at:0}),lastCandidateRef=useRef('');const[active,setActive]=useState(false),[status,setStatus]=useState('Ready to scan. A wanted list is optional.'),[match,setMatch]=useState(null),[candidate,setCandidate]=useState(null),[closer,setCloser]=useState(false),[barcode,setBarcode]=useState(null);
 const hapticWanted=()=>navigator.vibrate?.([100,50,100,50,220]);const hapticCandidate=()=>navigator.vibrate?.([30,30,30]);
 useEffect(()=>()=>{scanningRef.current=false;streamRef.current?.getTracks().forEach(t=>t.stop());workerRef.current?.terminate?.()},[]);
 async function start(){if(!navigator.mediaDevices?.getUserMedia){setStatus('Camera access is not available in this browser.');return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});streamRef.current=stream;videoRef.current.srcObject=stream;await videoRef.current.play();scanningRef.current=true;setActive(true);setMatch(null);setCandidate(null);setBarcode(null);setCloser(false);lastCandidateRef.current='';lastAlertRef.current={item:'',at:0};if('BarcodeDetector'in window){try{barcodeRef.current=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128']})}catch{barcodeRef.current=null}}if(window.Tesseract?.createWorker){workerRef.current=await window.Tesseract.createWorker('eng');}setStatus(wantedItems.length?'📷 Live scanning — visual recognition first, barcode assists when available.':'📷 Live scanning — visual recognition first.');scanLoop()}catch(e){setStatus(`Camera/scanner error: ${e?.message||'Unable to start camera.'}`)}}
 function stop(){scanningRef.current=false;ocrBusyRef.current=false;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;workerRef.current?.terminate?.();workerRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setActive(false);setStatus('Scanner stopped.')}
 async function scanLoop(){while(scanningRef.current){if(!ocrBusyRef.current)await scanFrame();await new Promise(r=>setTimeout(r,350))}}
 async function scanBarcode(video){if(!barcodeRef.current)return null;try{const codes=await barcodeRef.current.detect(video);return codes?.[0]?.rawValue||null}catch{return null}}
 async function ocrCanvas(canvas){if(!workerRef.current)return '';try{const ctx=canvas.getContext('2d');const{width,height}=canvas;ctx.filter='grayscale(1) contrast(1.35)';const full=await workerRef.current.recognize(canvas);let text=full?.data?.text||'';if(text.length<6){const crop=document.createElement('canvas');crop.width=Math.floor(width*.8);crop.height=height;crop.getContext('2d').drawImage(canvas,Math.floor(width*.1),0,crop.width,crop.height,0,0,crop.width,crop.height);const second=await workerRef.current.recognize(crop);text+=' '+(second?.data?.text||'')}return text}catch{return ''}}
 async function scanFrame(){ocrBusyRef.current=true;try{const video=videoRef.current;if(!video||video.readyState<2||!video.videoWidth)return;const canvas=document.createElement('canvas');const width=Math.min(1600,video.videoWidth);canvas.width=width;canvas.height=Math.floor(video.videoHeight*(width/video.videoWidth));canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const [text,code]=await Promise.all([ocrCanvas(canvas),scanBarcode(video)]);if(!scanningRef.current)return;if(code){setBarcode(code);if(!match&&wantedItems.some(x=>normalize(x).replace(/\s/g,'')===normalize(code).replace(/\s/g,''))){setMatch(wantedItems.find(x=>normalize(x).replace(/\s/g,'')===normalize(code).replace(/\s/g,'')));setCloser(false)}}const cleaned=text.replace(/[^a-zA-Z0-9'’:&\- ]/g,' ').replace(/\s+/g,' ').trim();if(cleaned.length<3)return;const wanted=matchWanted(cleaned,wantedItems);if(wanted){setMatch(wanted);setCandidate(null);setStatus('🎯 Wanted item detected — tap Look Closer for detailed identification.');const now=Date.now();if(lastAlertRef.current.item!==wanted||now-lastAlertRef.current.at>3500){hapticWanted();lastAlertRef.current={item:wanted,at:now}}}else if(cleaned.length>=6){const candidateKey=normalize(cleaned).slice(0,100);if(candidateKey!==lastCandidateRef.current){lastCandidateRef.current=candidateKey;setCandidate(cleaned.slice(0,120));setMatch(null);setStatus('🔎 Potential find detected — tap Look Closer to inspect it.');hapticCandidate()}}}finally{ocrBusyRef.current=false}}
 function lookCloser(){setCloser(true);setStatus('🔍 Close inspection mode — hold the camera steady on the item.');navigator.vibrate?.([60,30,60])}
 return <><Script src="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js" strategy="afterInteractive"/><div className="card"><h2>📷 Live Shelf Scanner</h2><p className="small">Visual/OCR recognition is primary. Barcode recognition assists when available. A wanted list is optional.</p><div className="scanner" style={{display:active?'block':'none'}}><video ref={videoRef} playsInline muted style={{width:'100%',minHeight:360,objectFit:'cover',display:'block'}}/><div className="scanHint">{closer?'Hold steady • inspecting item':'Move across the shelf • scanning automatically'}</div><div className="scanBox"/></div>{!active?<button className="scanBtn" onClick={start}>📷 Start Live Scan</button>:<button className="stopBtn" onClick={stop}>Stop Scanning</button>}<div className="status">{status}</div>{match&&<div className="scannerMatch">🎯 <b>WANTED: {match}</b><span>{barcode?` • Barcode ${barcode}`:''}</span><button type="button" onClick={lookCloser}>🔎 Look Closer</button></div>}{candidate&&<div className="scannerCandidate">✨ <b>Potential Find:</b> {candidate}{barcode?` • Barcode ${barcode}`:''}<button type="button" onClick={lookCloser}>🔎 Look Closer</button><small>Not confirmed rare — verify before buying.</small></div>}<p className="small">Wanted matches use a strong haptic pattern. Potential finds use a lighter pulse. Barcode is a secondary speed/confirmation layer.</p></div></>}
