'use client';
import Script from 'next/script';
import { useEffect,useRef,useState } from 'react';
const normalize=s=>(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function matchWanted(text,wantedItems){const n=normalize(text);if(n.length<3)return null;let best=null,bestScore=0;for(const item of wantedItems){const w=normalize(item);if(w.length<3)continue;if(n.includes(w)||w.includes(n))return item;const words=w.split(/\s+/).filter(x=>x.length>1);const hits=words.filter(x=>n.includes(x)).length;const score=words.length?hits/words.length:0;if(score>bestScore){bestScore=score;best=item}}return bestScore>=0.5?best:null}
export default function Scanner({wantedItems=[],media='book'}){const videoRef=useRef(null),streamRef=useRef(null),scanningRef=useRef(false),ocrBusyRef=useRef(false),lastAlertRef=useRef({item:'',at:0}),lastCandidateRef=useRef('');const[active,setActive]=useState(false),[status,setStatus]=useState('Ready to scan. A wanted list is optional.'),[match,setMatch]=useState(null),[candidate,setCandidate]=useState(null);
 const hapticWanted=()=>{if(navigator.vibrate)navigator.vibrate([100,50,100,50,220])};const hapticCandidate=()=>{if(navigator.vibrate)navigator.vibrate([30,30,30])};
 useEffect(()=>()=>stop(),[]);
 async function start(){if(!navigator.mediaDevices?.getUserMedia){setStatus('Camera access is not available in this browser.');return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});streamRef.current=stream;videoRef.current.srcObject=stream;await videoRef.current.play();scanningRef.current=true;setActive(true);setMatch(null);setCandidate(null);lastCandidateRef.current='';setStatus(wantedItems.length?'📷 Live scanning — checking your wanted list and potential finds.':'📷 Live scanning — looking for readable titles and potential finds.');scanLoop()}catch{setStatus('Camera permission was blocked. Allow camera access and try again.')}}
 function stop(){scanningRef.current=false;ocrBusyRef.current=false;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setActive(false);setStatus('Scanner stopped.')}
 async function scanLoop(){while(scanningRef.current){if(!ocrBusyRef.current&&window.Tesseract)await scanFrame();await new Promise(r=>setTimeout(r,700))}}
 async function scanFrame(){ocrBusyRef.current=true;try{const video=videoRef.current;if(!video||video.readyState<2||!video.videoWidth)return;const canvas=document.createElement('canvas');const width=Math.min(1600,video.videoWidth);const scale=width/video.videoWidth;canvas.width=width;canvas.height=Math.floor(video.videoHeight*scale);const ctx=canvas.getContext('2d');ctx.drawImage(video,0,0,canvas.width,canvas.height);const{data}=await window.Tesseract.recognize(canvas,'eng',{logger:()=>{}});if(!scanningRef.current)return;const text=data.text.replace(/[^a-zA-Z0-9'’:&\- ]/g,' ').replace(/\s+/g,' ').trim();if(text.length<3)return;const wanted=matchWanted(text,wantedItems);if(wanted){setMatch(wanted);setCandidate(null);setStatus('🎯 Wanted item detected');const now=Date.now();if(lastAlertRef.current.item!==wanted||now-lastAlertRef.current.at>3500){hapticWanted();lastAlertRef.current={item:wanted,at:now}}}else if(text.length>=6){const candidateKey=normalize(text).slice(0,80);if(candidateKey!==lastCandidateRef.current){lastCandidateRef.current=candidateKey;setCandidate(text.slice(0,100));setMatch(null);setStatus('🔎 Potential item detected');hapticCandidate()}}}catch{}finally{ocrBusyRef.current=false}}
 return <><Script src="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js" strategy="afterInteractive"/><div className="card"><h2>📷 Live Shelf Scanner</h2><p className="small">The scanner works without an account or wanted list. Move across a shelf and it will read visible text continuously.</p><div className="scanner" style={{display:active?'block':'none'}}><video ref={videoRef} playsInline muted style={{width:'100%',minHeight:360,objectFit:'cover',display:'block'}}/><div className="scanHint">Move across the shelf • scanning automatically</div><div className="scanBox"/></div>{!active?<button className="scanBtn" onClick={start}>📷 Start Live Scan</button>:<button className="stopBtn" onClick={stop}>Stop Scanning</button>}<div className="status">{status}</div>{match&&<div className="scannerMatch">🎯 <b>WANTED: {match}</b><span> — phone haptic alert sent</span></div>}{candidate&&<div className="scannerCandidate">✨ <b>Potential find:</b> {candidate}<small> Not confirmed rare — verify before buying.</small></div>}<p className="small">Wanted matches use a stronger haptic pattern. Unlisted readable items use a lighter pulse. Rarity is not confirmed by OCR alone.</p></div></>}
