'use client';
import Script from 'next/script';
import { useEffect,useRef,useState } from 'react';
const normalize=s=>(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function matchWanted(text,wantedItems){const n=normalize(text);if(n.length<2)return null;let best=null,bestScore=0;for(const item of wantedItems){const w=normalize(item);if(w.length<2)continue;if(n.includes(w)||w.includes(n))return item;const words=w.split(/\s+/).filter(x=>x.length>1);const hits=words.filter(x=>n.includes(x)).length;const score=words.length?hits/words.length:0;if(score>bestScore){bestScore=score;best=item}}return bestScore>=0.5?best:null}
export default function Scanner({wantedItems=[],media='book'}){const videoRef=useRef(null),streamRef=useRef(null),scanningRef=useRef(false),ocrBusyRef=useRef(false),barcodeBusyRef=useRef(false),lastAlertRef=useRef({item:'',at:0}),lastCandidateRef=useRef(''),barcodeDetectorRef=useRef(null);const[active,setActive]=useState(false),[status,setStatus]=useState('Ready to scan. A wanted list is optional.'),[match,setMatch]=useState(null),[candidate,setCandidate]=useState(null),[barcode,setBarcode]=useState(null);
 const hapticWanted=()=>{if(navigator.vibrate)navigator.vibrate([100,50,100,50,220])};const hapticCandidate=()=>{if(navigator.vibrate)navigator.vibrate([30,30,30])};
 useEffect(()=>{if('BarcodeDetector' in window){try{barcodeDetectorRef.current=new window.BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','isbn_10','isbn_13']})}catch{barcodeDetectorRef.current=null}}return()=>stop()},[]);
 async function start(){if(!navigator.mediaDevices?.getUserMedia){setStatus('Camera access is not available in this browser.');return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});streamRef.current=stream;videoRef.current.srcObject=stream;await videoRef.current.play();scanningRef.current=true;setActive(true);setMatch(null);setCandidate(null);setBarcode(null);lastCandidateRef.current='';setStatus(wantedItems.length?'📷 Live scanning — checking titles and barcodes.':'📷 Live scanning — recognizing titles and barcodes.');scanLoop()}catch{setStatus('Camera permission was blocked. Allow camera access and try again.')}}
 function stop(){scanningRef.current=false;ocrBusyRef.current=false;barcodeBusyRef.current=false;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setActive(false);setStatus('Scanner stopped.')}
 async function scanLoop(){while(scanningRef.current){if(!barcodeBusyRef.current)await scanBarcode();if(!ocrBusyRef.current&&window.Tesseract)await scanFrame();await new Promise(r=>setTimeout(r,350))}}
 async function scanBarcode(){const detector=barcodeDetectorRef.current,video=videoRef.current;if(!detector||!video||video.readyState<2||!video.videoWidth)return;barcodeBusyRef.current=true;try{const codes=await detector.detect(video);if(!scanningRef.current)return;for(const c of codes||[]){const value=c.rawValue;if(value){setBarcode(value);setStatus(`▥ Barcode detected: ${value}`);const wanted=matchWanted(value,wantedItems);if(wanted){setMatch(wanted);setCandidate(null);const now=Date.now();if(lastAlertRef.current.item!==wanted||now-lastAlertRef.current.at>3500){hapticWanted();lastAlertRef.current={item:wanted,at:now}}}}}}catch{}finally{barcodeBusyRef.current=false}}
 async function scanFrame(){ocrBusyRef.current=true;try{const video=videoRef.current;if(!video||video.readyState<2||!video.videoWidth)return;const canvas=document.createElement('canvas');const width=Math.min(1800,video.videoWidth);const scale=width/video.videoWidth;canvas.width=width;canvas.height=Math.floor(video.videoHeight*scale);const ctx=canvas.getContext('2d');ctx.drawImage(video,0,0,canvas.width,canvas.height);const{data}=await window.Tesseract.recognize(canvas,'eng',{logger:()=>{}});if(!scanningRef.current)return;const text=data.text.replace(/[^a-zA-Z0-9'’:&\- ]/g,' ').replace(/\s+/g,' ').trim();if(text.length<2)return;const wanted=matchWanted(text,wantedItems);if(wanted){setMatch(wanted);setCandidate(null);setStatus('🎯 Wanted item detected');const now=Date.now();if(lastAlertRef.current.item!==wanted||now-lastAlertRef.current.at>3500){hapticWanted();lastAlertRef.current={item:wanted,at:now}}}else if(text.length>=6){const candidateKey=normalize(text).slice(0,80);if(candidateKey!==lastCandidateRef.current){lastCandidateRef.current=candidateKey;setCandidate(text.slice(0,100));setMatch(null);setStatus('🔎 Potential item detected');hapticCandidate()}}}catch{}finally{ocrBusyRef.current=false}}
 return <><Script src="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js" strategy="afterInteractive"/><div className="card"><h2>📷 Live Shelf Scanner</h2><p className="small">Live recognition uses two methods: barcode detection when available, plus OCR for visible spine text. A wanted list is optional.</p><div className="scanner" style={{display:active?'block':'none'}}><video ref={videoRef} playsInline muted style={{width:'100%',minHeight:360,objectFit:'cover',display:'block'}}/><div className="scanHint">Move slowly across the shelf • keep spines inside the box</div><div className="scanBox"/></div>{!active?<button className="scanBtn" onClick={start}>📷 Start Live Scan</button>:<button className="stopBtn" onClick={stop}>Stop Scanning</button>}<div className="status">{status}</div>{match&&<div className="scannerMatch">🎯 <b>WANTED: {match}</b><span> — strong haptic alert sent</span></div>}{candidate&&<div className="scannerCandidate">✨ <b>Potential item:</b> {candidate}<small> Not confirmed rare or valuable.</small></div>}{barcode&&<div className="small">Last barcode: {barcode}</div>}<p className="small">The barcode layer is more reliable than OCR when a book or media item has a readable UPC/EAN/ISBN barcode. Rarity still requires separate market data.</p></div></>}
